language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  bash deploy-documentation.sh
env:
  global:
    - secure: KKZlBxi/eNnz2wV4tF1/8TSWKxfY8SY45MIUgbyoTqcG7Bka14Lc3+g8/prcheidHc7OI2Kr9pbh1lG9a43fdg3OcanjNwRYN06ZW9QYb/FUV6qwKadmH6uKU8axyGuP0m2rWYcHeB/Sd63GkDuk25CtmjxuhneXqLivOkyhl84buHrDrJiWHnxYvv4OXLHiHJOHHoAlIHHo6rYTnB/Artl+LDZdfGHRw8zSnRLfRNZyQews1S0DSuokluGbhiPrYGNVqkGVu6oYTRXzoXwMZ9+Sgxzpn1DGi+MOBBJYIXghbaii0WzGBaLsRtRDZ4kVh+V1HfSnwU5QN30uYNKMKKCS1IdmSfY1l2A2L9p2SOrT10NnbqrlVQmAj3hwyIW9usYvtNlTxGQcGwOHs40ghFO2R68bSIP9DTcIYvwIujpo67BKemNLoNsI4wfPl8J7B+8C6D08WKCfR6jinIzjKxR4PF6H/plNYL6EKIo2gK7Kn1Jgxqr1zEIqHqEAsBEqZ2hwowzvNi6N/gjrD1jw3xrQqkxYsKRPG4Q0rOYpK9hocA6RJwoP2deGWuAELFCwZhZiCjVbPY969b3IBT0jQvqdu0GD3iQ2u9izTG+65w8p4CLQDL5ofES7dohvnWiUoLP42typBRacs0/xbOMoEV+hMLaJovOpD280rTx4cPs=
